apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-mongo-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: standard
  hostPath:
    path: /home/c/metrics_mongo